PRODUCT_COPY_FILES += \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libandroidfw.so:system/lib/vndk-27/libandroidfw.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libandroid_runtime.so:system/lib/vndk-27/libandroid_runtime.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libandroid.so:system/lib/vndk-27/libandroid.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libappfuse.so:system/lib/vndk-27/libappfuse.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libaudioclient.so:system/lib/vndk-27/libaudioclient.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libaudiomanager.so:system/lib/vndk-27/libaudiomanager.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libcamera_client.so:system/lib/vndk-27/libcamera_client.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libdebuggerd_client.so:system/lib/vndk-27/libdebuggerd_client.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libdng_sdk.so:system/lib/vndk-27/libdng_sdk.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libdrmframework.so:system/lib/vndk-27/libdrmframework.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libeffectsconfig.so:system/lib/vndk-27/libeffectsconfig.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libEGL.so:system/lib/vndk-27/libEGL.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libETC1.so:system/lib/vndk-27/libETC1.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libGLESv2.so:system/lib/vndk-27/libGLESv2.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libGLESv3.so:system/lib/vndk-27/libGLESv3.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libgraphicsenv.so:system/lib/vndk-27/libgraphicsenv.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libharfbuzz_ng.so:system/lib/vndk-27/libharfbuzz_ng.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libheif.so:system/lib/vndk-27/libheif.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libhwui.so:system/lib/vndk-27/libhwui.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libicui18n.so:system/lib/vndk-27/libicui18n.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libicuuc.so:system/lib/vndk-27/libicuuc.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libimg_utils.so:system/lib/vndk-27/libimg_utils.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libinput.so:system/lib/vndk-27/libinput.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libjavacore.so:system/lib/vndk-27/libjavacore.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libjnigraphics.so:system/lib/vndk-27/libjnigraphics.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libkeystore_binder.so:system/lib/vndk-27/libkeystore_binder.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/liblogwrap.so:system/lib/vndk-27/liblogwrap.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libmediadrm.so:system/lib/vndk-27/libmediadrm.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libmediametrics.so:system/lib/vndk-27/libmediametrics.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libmedia.so:system/lib/vndk-27/libmedia.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libmediautils.so:system/lib/vndk-27/libmediautils.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libmemunreachable.so:system/lib/vndk-27/libmemunreachable.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libminikin.so:system/lib/vndk-27/libminikin.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libnativebridge.so:system/lib/vndk-27/libnativebridge.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libnativehelper.so:system/lib/vndk-27/libnativehelper.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libnativeloader.so:system/lib/vndk-27/libnativeloader.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libnetd_client.so:system/lib/vndk-27/libnetd_client.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libpackagelistparser.so:system/lib/vndk-27/libpackagelistparser.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libpdfium.so:system/lib/vndk-27/libpdfium.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libpowermanager.so:system/lib/vndk-27/libpowermanager.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libprocessgroup.so:system/lib/vndk-27/libprocessgroup.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libRScpp.so:system/lib/vndk-27/libRScpp.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libselinux.so:system/lib/vndk-27/libselinux.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libsensorservice.so:system/lib/vndk-27/libsensorservice.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libsensor.so:system/lib/vndk-27/libsensor.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libskia.so:system/lib/vndk-27/libskia.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libsoftkeymaster.so:system/lib/vndk-27/libsoftkeymaster.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libsonivox.so:system/lib/vndk-27/libsonivox.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libsoundtrigger.so:system/lib/vndk-27/libsoundtrigger.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libsparse.so:system/lib/vndk-27/libsparse.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libstagefright.so:system/lib/vndk-27/libstagefright.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libstdc++.so:system/lib/vndk-27/libstdc++.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libvintf.so:system/lib/vndk-27/libvintf.so \
	vendor/samsung/universal9810-common/vendor_vndk/vndk-27-arm32/libvulkan.so:system/lib/vndk-27/libvulkan.so 

